language: node_js
node_js:
  - "10.11"
install:
  - npm install
script:
  - npm test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build; fi
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master